## Configurando o MySQL com Python

Neste momento, vamos configurar a integração entre o MySQL e Python. Isso nos permitirá executar consultas, inserções e outras operações no banco de dados MySQL usando o Python como nossa linguagem de programação principal.

In [2]:

def connect_mysql(host_name, user_name, pw):
    cnx = mysql.connector.connect(
        host = host_name,
        user = user_name,
        password = pw
    )
    
    return cnx

In [7]:
a = connect_mysql('localhost','orlando_bussolo', 'asdfg...')

<mysql.connector.connection_cext.CMySQLConnection object at 0x7f2b7da7ca60>

Criaremos um cursor, que é um objeto utilizado para executar instruções SQL no contexto do Python. Essse cursor nos permitirá enviar consultas e comandos SQL para o banco de dados MySQL por meio da conexão estabelecida e obter os resultados de volta para serem processados em nosso código Python

In [12]:
def create_cursor(cnx):
    cursor = cnx.cursor()
    return cursor
    print(cursor)

In [15]:
b = create_cursor(a)

## Criando uma base de dados

O método `execute()` é usado para compilar uma instrução SQL

('db_games',)
('information_schema',)
('mysql',)
('performance_schema',)
('sys',)

In [29]:
cursor.execute("USE db_games")
cursor.execute("SHOW TABLES")
for a in cursor:
    print(a)

('premiere_league',)

In [14]:
def create_database(cursor, db_name):
    cursor.execute(f"CREATE DATABASE IF NOT EXISTS,{db_name}")
    print(f"\nBase de dados {db_name} criada")

## Criando uma tabela

Antes de criar nossa tabela, vamos revisar as colunas necessárias que precisaremos incluir nela. Essa etapa é importante para garantir que nossa tabela seja projetada corretamente, atendendo aos requisitos de armazenamento e organização dos dados.

In [ ]:
 df = pd.read_csv("/home/orlando_linux/pipeline-python-mongo-mysql/data_teste/tabela.csv")

**Selecionando a base de dados para verificar a tabela criada**

## Inserindo os dados do csv na tabela

Para inserir os dados na tabela do MySQL, é necessário percorrer cada linha do DataFrame e transformá-las em tuplas. Essa abordagem permite que mapeemos os dados do DataFrame para as colunas correspondentes da tabela do MySQL de forma eficiente e precisa.

In [1]:
import mysql.connector
import pandas as pd

cnx = mysql.connector.connect(
        host = 'localhost',
        user = 'orlando_bussolo',
        password = 'asdfg...'
    )

cursor = cnx.cursor()
cursor.execute("CREATE DATABASE IF NOT EXISTS db_games")

cursor.execute("SHOW DATABASES")
for x in cursor:
    print(x)

('db_games',)
('information_schema',)
('mysql',)
('performance_schema',)
('sys',)

In [2]:
cursor.execute("""
        CREATE TABLE IF NOT EXISTS db_games.premiere_league(
        
        match_id INT,
        league_id INT,
        match_date DATE,
        match_time TIME,
        match_hometeam_id INT,
        match_hometeam_name VARCHAR(255),
        match_hometeam_score INT,
        match_awayteam_name VARCHAR(255),
        match_awayteam_id INT,
        match_awayteam_score INT,
        match_round INT,
        match_stadium VARCHAR(255),
        match_referee VARCHAR(255),
        league_year VARCHAR(50),
                
        PRIMARY KEY (match_id)
    )""")

In [3]:
cursor.execute("USE db_games")
cursor.execute("SHOW TABLES")
for x in cursor:
    print(x)

('premiere_league',)

In [4]:
 df = pd.read_csv("/home/orlando_linux/pipeline-python-mongo-mysql/data_teste/tabela.csv")
df.head(1)

,match_id,league_id,match_date,match_time,match_hometeam_id,match_hometeam_name,match_hometeam_score,match_awayteam_name,match_awayteam_id,match_awayteam_score,match_round,match_stadium,match_referee,league_year
0,206506,152,2024-01-30,21:15,3088,Aston Villa,1.0,Newcastle United,3100,3.0,22,Villa Park (Birmingham),J. Brooks,2023/2024

In [5]:
for i, row in df.iterrows():
    tuple(row)

In [12]:
import numpy as np
lista = [tuple(row) for i, row in df.iterrows() ]
lista = [tuple(None if pd.isna(item) else item for item in tupla) for tupla in lista]


print(lista)

[(206506, 152, '2024-01-30', '21:15', 3088, 'Aston Villa', 1.0, 'Newcastle United', 3100, 3.0, 22, 'Villa Park (Birmingham)', 'J. Brooks', '2023/2024'), (206507, 152, '2024-01-30', '20:45', 3085, 'Fulham', 0.0, 'Everton', 3073, 0.0, 22, 'Craven Cottage (London)', 'T. Bramall', '2023/2024'), (206508, 152, '2024-01-30', '20:45', 3091, 'Luton Town', 4.0, 'Brighton & Hove Albion', 3079, 0.0, 22, 'Kenilworth Road (Luton, Bedfordshire)', 'R. Jones', '2023/2024'), (206509, 152, '2024-01-30', '20:30', 3089, 'Nottingham Forest', 1.0, 'Arsenal', 141, 2.0, 22, 'The City Ground (Nottingham, Nottinghamshire)', 'S. Hooper', '2023/2024'), (206513, 152, '2024-01-30', '21:00', 3429, 'Crystal Palace', 3.0, 'Sheffield United', 3074, 2.0, 22, 'Selhurst Park (London)', 'T. Harrington', '2023/2024'), (206510, 152, '2024-01-31', '20:30', 164, 'Tottenham Hotspur', 3.0, 'Brentford', 3086, 2.0, 22, 'Tottenham Hotspur Stadium (London)', 'D. Coote', '2023/2024'), (206514, 152, '2024-01-31', '21:15', 84, 'Liverpool', 4.0, 'Chelsea', 88, 1.0, 22, 'Anfield (Liverpool)', 'P. Tierney', '2023/2024'), (206515, 152, '2024-01-31', '20:30', 80, 'Manchester City', 3.0, 'Burnley', 3075, 1.0, 22, 'Etihad Stadium (Manchester)', 'S. Barrott', '2023/2024'), (206511, 152, '2024-02-01', '20:30', 3081, 'West Ham United', 1.0, 'AFC Bournemouth', 3071, 1.0, 22, 'London Stadium (London)', 'T. Robinson', '2023/2024'), (206512, 152, '2024-02-01', '21:15', 3077, 'Wolverhampton Wanderers', 3.0, 'Manchester United', 102, 4.0, 22, 'Molineux Stadium (Wolverhampton, West Midlands)', 'J. Gillett', '2023/2024'), (206525, 152, '2024-02-03', '18:30', 3074, 'Sheffield United', 0.0, 'Aston Villa', 3088, 5.0, 23, 'Bramall Lane (Sheffield)', 'P. Tierney', '2023/2024'), (206524, 152, '2024-02-03', '16:00', 3100, 'Newcastle United', 4.0, 'Luton Town', 3091, 4.0, 23, "St. James' Park (Newcastle upon Tyne)", 'T. Bramall', '2023/2024'), (206522, 152, '2024-02-03', '13:30', 3073, 'Everton', 2.0, 'Tottenham Hotspur', 164, 2.0, 23, 'Goodison Park (Liverpool)', 'M. Oliver', '2023/2024'), (206520, 152, '2024-02-03', '16:00', 3075, 'Burnley', 2.0, 'Fulham', 3085, 2.0, 23, 'Turf Moor (Burnley)', 'D. Bond', '2023/2024'), (206519, 152, '2024-02-03', '16:00', 3079, 'Brighton & Hove Albion', 4.0, 'Crystal Palace', 3429, 1.0, 23, 'American Express Stadium (Falmer, East Sussex)', 'S. Hooper', '2023/2024'), (206517, 152, '2024-02-04', '17:30', 141, 'Arsenal', 3.0, 'Liverpool', 84, 1.0, 23, 'Emirates Stadium (London)', 'A. Taylor', '2023/2024'), (206521, 152, '2024-02-04', '15:00', 88, 'Chelsea', 2.0, 'Wolverhampton Wanderers', 3077, 4.0, 23, 'Stamford Bridge (London)', 'T. Robinson', '2023/2024'), (206516, 152, '2024-02-04', '15:00', 3071, 'AFC Bournemouth', 1.0, 'Nottingham Forest', 3089, 1.0, 23, 'Vitality Stadium (Bournemouth, Dorset)', 'R. Welch', '2023/2024'), (206523, 152, '2024-02-04', '15:00', 102, 'Manchester United', 3.0, 'West Ham United', 3081, 0.0, 23, 'Old Trafford (Manchester)', 'A. Madley', '2023/2024'), (206518, 152, '2024-02-05', '21:00', 3086, 'Brentford', 1.0, 'Manchester City', 80, 3.0, 23, 'Gtech Community Stadium (Brentford, Middlesex)', 'J. Gillett', '2023/2024'), (206530, 152, '2024-02-10', '16:00', 3091, 'Luton Town', 1.0, 'Sheffield United', 3074, 3.0, 24, 'Kenilworth Road (Luton, Bedfordshire)', 'C. Kavanagh', '2023/2024'), (206531, 152, '2024-02-10', '13:30', 80, 'Manchester City', 2.0, 'Everton', 3073, 0.0, 24, 'Etihad Stadium (Manchester)', 'J. Brooks', '2023/2024'), (206535, 152, '2024-02-10', '16:00', 3077, 'Wolverhampton Wanderers', 0.0, 'Brentford', 3086, 2.0, 24, 'Molineux Stadium (Wolverhampton, West Midlands)', 'S. Hooper', '2023/2024'), (206532, 152, '2024-02-10', '18:30', 3089, 'Nottingham Forest', 2.0, 'Newcastle United', 3100, 3.0, 24, 'The City Ground (Nottingham, Nottinghamshire)', 'A. Taylor', '2023/2024'), (206533, 152, '2024-02-10', '16:00', 164, 'Tottenham Hotspur', 2.0, 'Brighton & Hove Albion', 3079, 1.0, 24, 'Tottenham Hotspur Stadium (London)', 'S. Barrott', '2023/2024'), (206529, 152, '2024-02-10', '16:00', 84, 'Liverpool', 3.0, 'Burnley', 3075, 1.0, 24, 'Anfield (Liverpool)', 'T. Robinson', '2023/2024'), (206528, 152, '2024-02-10', '16:00', 3085, 'Fulham', 3.0, 'AFC Bournemouth', 3071, 1.0, 24, 'Craven Cottage (London)', 'D. England', '2023/2024'), (206526, 152, '2024-02-11', '17:30', 3088, 'Aston Villa', 1.0, 'Manchester United', 102, 2.0, 24, 'Villa Park (Birmingham)', 'R. Jones', '2023/2024'), (206534, 152, '2024-02-11', '15:00', 3081, 'West Ham United', 0.0, 'Arsenal', 141, 6.0, 24, 'London Stadium (London)', 'C. Pawson', '2023/2024'), (206527, 152, '2024-02-12', '21:00', 3429, 'Crystal Palace', 1.0, 'Chelsea', 88, 3.0, 24, 'Selhurst Park (London)', 'M. Oliver', '2023/2024'), (206539, 152, '2024-02-17', '16:00', 3085, 'Fulham', 1.0, 'Aston Villa', 3088, 2.0, 25, 'Craven Cottage (London)', 'L. Smith', '2023/2024'), (206541, 152, '2024-02-17', '18:30', 80, 'Manchester City', 1.0, 'Chelsea', 88, 1.0, 25, 'Etihad Stadium (Manchester)', 'A. Madley', '2023/2024'), (206545, 152, '2024-02-17', '16:00', 164, 'Tottenham Hotspur', 1.0, 'Wolverhampton Wanderers', 3077, 2.0, 25, 'Tottenham Hotspur Stadium (London)', 'A. Taylor', '2023/2024'), (206542, 152, '2024-02-17', '16:00', 3100, 'Newcastle United', 2.0, 'AFC Bournemouth', 3071, 2.0, 25, "St. James' Park (Newcastle upon Tyne)", 'M. Salisbury', '2023/2024'), (206543, 152, '2024-02-17', '16:00', 3089, 'Nottingham Forest', 2.0, 'West Ham United', 3081, 0.0, 25, 'The City Ground (Nottingham, Nottinghamshire)', 'T. Bramall', '2023/2024'), (206537, 152, '2024-02-17', '16:00', 3075, 'Burnley', 0.0, 'Arsenal', 141, 5.0, 25, 'Turf Moor (Burnley)', 'J. Gillett', '2023/2024'), (206536, 152, '2024-02-17', '13:30', 3086, 'Brentford', 1.0, 'Liverpool', 84, 4.0, 25, 'Gtech Community Stadium (Brentford, Middlesex)', 'M. Oliver', '2023/2024'), (206540, 152, '2024-02-18', '17:30', 3091, 'Luton Town', 1.0, 'Manchester United', 102, 2.0, 25, 'Kenilworth Road (Luton, Bedfordshire)', 'D. Coote', '2023/2024'), (206544, 152, '2024-02-18', '15:00', 3074, 'Sheffield United', 0.0, 'Brighton & Hove Albion', 3079, 5.0, 25, 'Bramall Lane (Sheffield)', 'S. Attwell', '2023/2024'), (206538, 152, '2024-02-19', '21:00', 3073, 'Everton', 1.0, 'Crystal Palace', 3429, 1.0, 25, 'Goodison Park (Liverpool)', 'P. Tierney', '2023/2024'), (206471, 152, '2024-02-20', '20:30', 80, 'Manchester City', 1.0, 'Brentford', 3086, 0.0, 18, 'Etihad Stadium (Manchester)', 'D. England', '2023/2024'), (206552, 152, '2024-02-21', '20:30', 84, 'Liverpool', 4.0, 'Luton Town', 3091, 1.0, 26, 'Anfield (Liverpool)', 'A. Madley', '2023/2024'), (206550, 152, '2024-02-23', '21:00', 88, 'Chelsea', None, 'Tottenham Hotspur', 164, None, 26, 'Stamford Bridge (London)', None, '2023/2024'), (206546, 152, '2024-02-24', '18:30', 3071, 'AFC Bournemouth', 0.0, 'Manchester City', 80, 1.0, 26, 'Vitality Stadium (Bournemouth, Dorset)', 'J. Gillett', '2023/2024'), (206547, 152, '2024-02-24', '21:00', 141, 'Arsenal', 4.0, 'Newcastle United', 3100, 1.0, 26, 'Emirates Stadium (London)', 'P. Tierney', '2023/2024'), (206548, 152, '2024-02-24', '16:00', 3088, 'Aston Villa', 4.0, 'Nottingham Forest', 3089, 2.0, 26, 'Villa Park (Birmingham)', 'S. Barrott', '2023/2024'), (206549, 152, '2024-02-24', '16:00', 3079, 'Brighton & Hove Albion', 1.0, 'Everton', 3073, 1.0, 26, 'American Express Stadium (Falmer, East Sussex)', 'T. Harrington', '2023/2024'), (206551, 152, '2024-02-24', '16:00', 3429, 'Crystal Palace', 3.0, 'Burnley', 3075, 0.0, 26, 'Selhurst Park (London)', 'L. Smith', '2023/2024'), (206553, 152, '2024-02-24', '16:00', 102, 'Manchester United', 1.0, 'Fulham', 3085, 2.0, 26, 'Old Trafford (Manchester)', 'M. Oliver', '2023/2024'), (206555, 152, '2024-02-25', '14:30', 3077, 'Wolverhampton Wanderers', 1.0, 'Sheffield United', 3074, 0.0, 26, 'Molineux Stadium (Wolverhampton, West Midlands)', 'D. Bond', '2023/2024'), (206554, 152, '2024-02-26', '21:00', 3081, 'West Ham United', 4.0, 'Brentford', 3086, 2.0, 26, 'London Stadium (London)', 'S. Hooper', '2023/2024'), (206560, 152, '2024-03-02', '18:30', 3091, 'Luton Town', 2.0, 'Aston Villa', 3088, 3.0, 27, 'Kenilworth Road (Luton, Bedfordshire)', 'M. Oliver', '2023/2024'), (206565, 152, '2024-03-02', '16:00', 164, 'Tottenham Hotspur', 3.0, 'Crystal Palace', 3429, 1.0, 27, 'Tottenham Hotspur Stadium (London)', 'J. Brooks', '2023/2024'), (206563, 152, '2024-03-02', '16:00', 3089, 'Nottingham Forest', 0.0, 'Liverpool', 84, 1.0, 27, 'The City Ground (Nottingham, Nottinghamshire)', 'P. Tierney', '2023/2024'), (206562, 152, '2024-03-02', '16:00', 3100, 'Newcastle United', 3.0, 'Wolverhampton Wanderers', 3077, 0.0, 27, "St. James' Park (Newcastle upon Tyne)", 'T. Robinson', '2023/2024'), (206558, 152, '2024-03-02', '16:00', 3073, 'Everton', 1.0, 'West Ham United', 3081, 3.0, 27, 'Goodison Park (Liverpool)', 'C. Pawson', '2023/2024'), (206556, 152, '2024-03-02', '16:00', 3086, 'Brentford', 2.0, 'Chelsea', 88, 2.0, 27, 'Gtech Community Stadium (Brentford, Middlesex)', 'J. Gillett', '2023/2024'), (206559, 152, '2024-03-02', '16:00', 3085, 'Fulham', 3.0, 'Brighton & Hove Albion', 3079, 0.0, 27, 'Craven Cottage (London)', 'S. Hooper', '2023/2024'), (206561, 152, '2024-03-03', '16:30', 80, 'Manchester City', 3.0, 'Manchester United', 102, 1.0, 27, 'Etihad Stadium (Manchester)', 'A. Madley', '2023/2024'), (206557, 152, '2024-03-03', '14:00', 3075, 'Burnley', 0.0, 'AFC Bournemouth', 3071, 2.0, 27, 'Turf Moor (Burnley)', 'D. Coote', '2023/2024'), (206564, 152, '2024-03-04', '21:00', 3074, 'Sheffield United', 0.0, 'Arsenal', 141, 6.0, 27, 'Bramall Lane (Sheffield)', 'S. Barrott', '2023/2024'), (206567, 152, '2024-03-09', '18:30', 141, 'Arsenal', 2.0, 'Brentford', 3086, 1.0, 28, 'Emirates Stadium (London)', 'R. Jones', '2023/2024'), (206575, 152, '2024-03-09', '16:00', 3077, 'Wolverhampton Wanderers', 2.0, 'Fulham', 3085, 1.0, 28, 'Molineux Stadium (Wolverhampton, West Midlands)', 'T. Harrington', '2023/2024'), (206573, 152, '2024-03-09', '13:30', 102, 'Manchester United', 2.0, 'Everton', 3073, 0.0, 28, 'Old Trafford (Manchester)', 'S. Hooper', '2023/2024'), (206571, 152, '2024-03-09', '16:00', 3429, 'Crystal Palace', 1.0, 'Luton Town', 3091, 1.0, 28, 'Selhurst Park (London)', 'S. Singh', '2023/2024'), (206566, 152, '2024-03-09', '16:00', 3071, 'AFC Bournemouth', 2.0, 'Sheffield United', 3074, 2.0, 28, 'Vitality Stadium (Bournemouth, Dorset)', 'A. Taylor', '2023/2024'), (206569, 152, '2024-03-10', '15:00', 3079, 'Brighton & Hove Albion', 1.0, 'Nottingham Forest', 3089, 0.0, 28, 'American Express Stadium (Falmer, East Sussex)', 'M. Salisbury', '2023/2024'), (206568, 152, '2024-03-10', '14:00', 3088, 'Aston Villa', 0.0, 'Tottenham Hotspur', 164, 4.0, 28, 'Villa Park (Birmingham)', 'C. Kavanagh', '2023/2024'), (206572, 152, '2024-03-10', '16:45', 84, 'Liverpool', 1.0, 'Manchester City', 80, 1.0, 28, 'Anfield (Liverpool)', 'M. Oliver', '2023/2024'), (206574, 152, '2024-03-10', '15:00', 3081, 'West Ham United', 2.0, 'Burnley', 3075, 2.0, 28, 'London Stadium (London)', 'D. England', '2023/2024'), (206570, 152, '2024-03-11', '21:00', 88, 'Chelsea', 3.0, 'Newcastle United', 3100, 2.0, 28, 'Stamford Bridge (London)', 'J. Brooks', '2023/2024'), (206456, 152, '2024-03-13', '20:30', 3071, 'Bournemouth', 4.0, 'Luton', 3091, 3.0, 17, 'Vitality Stadium (Bournemouth, Dorset)', 'S. Allison', '2023/2024')]

In [13]:

sql = "INSERT INTO db_games.premiere_league VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s);"

cursor.executemany(sql, lista)
#print(f"\n {cursor.rowcount} dados foram inseridos na tabela premiere_league.")
cnx.commit()

## Visualizando os dados inseridos